---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: familie-ef-soknad
  namespace: default
  labels:
    team: teamfamilie
spec:
  image: navikt/familie-ef-soknad:{{version}}
  team: {{team}}
  port: 8080
  ingresses:
    - {{ingress1}}
    - {{ingress2}}
  liveness:
    path: {{baseurl}}/internal/isAlive
    initialDelay: 10
  readiness:
    path: {{baseurl}}/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  resources:
    limits:
      cpu: '3'
      memory: 768Mi
    requests:
      memory: 512Mi