version: 2.1
orbs:
  nais: 'navikt/nais-deployment@1.1.0'

executors:
  nais-deployer:
    environment:
      TEAM: teamfamilie
    docker:
      - image: navikt/deployment-cli:latest

jobs:
  build:
    docker:
      - image: circleci/node:11.7.0
    steps:
      - checkout
      - setup_remote_docker:
            docker_layer_caching: true
      - run:
          name: Generate version number, github token and docker image tags
          command: |
            export VERSION="$(node -p "require('./package').version")-$CIRCLE_SHA1"
            echo "export VERSION="$(node -p "require('./package').version")-$CIRCLE_SHA1"" >> properties.env
            echo "export DOCKER_TAG=\"$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$VERSION\"" >> properties.env
            cat properties.env >> $BASH_ENV
      - run:
          name: Installer npm pakker
          command: |
            npm ci
      - run:
          name: Bygg React app
          command: |
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build/*


  deploy_docker:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Set up environment variables
          command: cat /home/circleci/project/properties.env >> $BASH_ENV
      - run:
          name: Slett test resources
          command: rm -rf development
      - run:
          name: Bygger Docker image
          command: |
            echo $DOCKER_TAG $VERSION
            docker build -t $DOCKER_TAG .
      - run:
          name: Docker push
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_LOGIN" --password-stdin
            echo "Pushing with tag $DOCKER_TAG"
            docker push $DOCKER_TAG
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - properties.env

  deploy_dev:
    executor: nais-deployer
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - checkout
      - run:
          name: Set up environment variables
          command: cat /home/circleci/project/properties.env >> $BASH_ENV
      - run:
          name: Create github deployment for stable test
          command: |
            deployment-cli deploy create \
            --cluster=dev-sbs \
            --repository=$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME \
            --appid=${GITHUB_APP_ID} \
            --key-base64=${GITHUB_PRIVATE_KEY} \
            --team=${TEAM} \
            --version=${VERSION} \
            --resource=./nais.config.yaml

workflows:
  version: 2
  build_n_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+$/
      - deploy_docker:
          context: NAIS deployment
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+$/
      - deploy_dev:
          context: familie-ci
          requires:
            - deploy_docker
          filters:
            tags:
              only: /^.*/
            branches:
              only: /.*/